name: firestore_converter_workshop
description: The demo app for this workshop.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0'
  flutter: '>=2.0.0'

dependencies:
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  provider: ^6.0.2

flutter:
  uses-material-design: true
